---
title: "About Rebecca"
type: "about"
date: "2016-05-05T21:48:51-07:00"
---

Hi there! I'm Rebecca Barter. I'm so glad you've made it to my page.

I'm a statistician, data scientist, educator, and communicator who has a dual passion for empowering others by teaching critical thinking and technical skills for data science, and for uncovering the hidden patterns and stories that live inside complex datasets (primarily related to healthcare and medicine). I spend most of my time working towards improving current approaches to teaching statistics, data literacy and communication, both at introductory and advanced levels, and conducting deep dives into healthcare data, developing predictive models and producing explanatory data visualizations.

**I am currently looking for a job**! My ideal job will involve working on a team of (data- *and* regular-) scientists who are analyzing healthcare-related data to answer a real-world scientific question. Ideally, said team would focus on actually implementing the solutions to the problems they are working on (rather than *just* writing papers about them - although this is important too!). I love spending my time cleaning messy data, exploring it, and communicating what I find (especially in the form of data viz). I also have a lot of experience fitting predictive models and doing causal inference! I'm currently focusing my search on non-profit and university research institutions that are preferably remote-friendly (depending on location). Please reach out if I sound like I might be a good fit for your team or research group!

Originally from Australia, I moved to California in 2014 and graduated from my PhD in Statistics at UC Berkeley in December 2019, during which time I was advised primarily by Prof Bin Yu. During much of my PhD I was a Data Science Fellow at the [Berkeley Institute for Data Science (BIDS)](https://bids.berkeley.edu). My PhD research focused on data science in healthcare (such as predicting surgical site infections using electronic health records, and using causal inference to investigate the impact of liver transplant wait time on survival). 

As an experienced educator, certified RStudio instructor, and certified Software Carpentry instructor, I have been the primary lecture for an undergraduate statistics course at UC Berkeley, I have taught more than 20 R and data science-related workshops, and have helped hundreds of thousands of people worldwide learn R and statistics through this blog.

My primary upcoming project is a book, "*Veridical Data Science: The Practice of Responsible Data Analysis and Decision Making*", that I am co-authoring with my PhD advisor and ongoing mentor, Professor Bin Yu. Veridical Data Science combines Professor Yu's decades-long experience in the field of data science and her innovative [Veridical Data Science framework](https://www.pnas.org/content/117/8/3920) with my enthusiasm for explaining complex data science topics in a simple and intuitive way. We hope that *Veridical Data Science* can be a practical handbook for new (and old) Data Scientists, highlighting the role of judgment calls and critical thinking in data science, and we hope that it will play a significant role in the education of the next generation of data scientists. *Veridical Data Science* will be published by MIT Press sometime in 2023. Stay tuned!

<!-- In the past, I have dabbled in writing software as the author of the [superheat](https://github.com/rlbarter/superheat) R package for creating beautiful and customizable heatmaps in R. -->

<!-- When I'm not doing R or stats stuff, I'm usually found hiking, climbing rocks somewhere, taking photos of beautiful places, painting, or throwing mugs and bowls at the pottery studio! -->

If you've found my blogs helpful and want to buy me a coffee or tea, feel free to contribute over at https://ko-fi.com/rlbarter. 

<!-- If you want to work with me, or learn R or statistics directly from me, I'm available for private coaching and consulting! Email me at rebeccabarter@berkeley.edu to inquire. -->
