---
title: "Rebecca's CV"
date: "2016-05-05T21:48:51-07:00"
---

## Experience

August 2016 - Present **Data Science Fellow**,
*Berkeley Institute of Data Science, University of
California, Berkeley*

August 2014 - May 2016 **Graduate Student Researcher (GSR)**,
*Department of Statistics, University of
California, Berkeley*

<!--
November 2016 - present **Visiting Student**,
*Department of Surgery, University of
California, San Francisco*
-->

May 2016 - August 2016 **Quantitative Analyst Intern**,
*Google, Seattle*

Spring 2015, Fall 2016 **Statistical Consultant**,
*Department of Statistics, University of
California, Berkeley*

February 2014 - July 2014 **Research Assistant**,
*Melanoma Institute Australia and School of Mathematics and
Statistics, The University of Sydney Australia*

------

## Education
(current) **PhD, Statistics** , *University of
California, Berkeley*, Expected Graduation 2020

**Bachelor of Science (Advanced)
(First Class Honours and University Medal in Statistics)**,
*The University of
Sydney, Australia*, Graduated November 2013

------

## Publications

**Barter RL**, Yu B (2018). Superheat: Supervised heatmaps for visualizing
complex data, *Journal Of Computational And Graphical Statistics* [www.tandfonline.com/doi/abs/10.1080/10618600.2018.1473780](https://www.tandfonline.com/doi/abs/10.1080/10618600.2018.1473780)


**Barter RL**, Schramm SJ, Mann GJ, and Yang YH (2014). Network-based biomarkers enhance classical approaches to prognostic gene expression signatures, *BMC Systems Biology* [www.biomedcentral.com/1752-0509/8/S4/S5](http://www.biomedcentral.com/1752-0509/8/S4/S5)


### On the web

**Barter RL**, Yu B (2017). Superheat: creating beautiful and extendable heatmaps for visualizing complex data in R. [*IBS Biometric Bulletin*](https://www.biometricsociety.org/wp-content/uploads/2018/04/10-012_IBS_Bulletin_REV.pdf)

**Barter RL**, Shrotriya S (2016). Integrated Data Analysis for Early Warning of Lung Failure. The Geisinger Collider Competition Winning Project. *ODBMS* [http://www.odbms.org/2016/06/integrated-data-analysis-for-early-warning-of-lung-failure/](http://www.odbms.org/2016/06/integrated-data-analysis-for-early-warning-of-lung-failure/)
                    
                  
------

## Software

[**superheat**](https://github.com/rlbarter/superheat), An R package with tools for visualizing and exploring data using supervised heatmaps.
                    
------
					
## Teaching Experience

### Semester-long classes

Fall 2017 **Graduate Student Instructor (GSI)**,
*Department of Statistics, University of
California, Berkeley*

- [STAT215A](/teaching#stat215a) Statistical Models: Theory and Applications


Spring 2015 **Graduate Student Instructor (GSI)**,
*Department of Statistics, University of
California, Berkeley*

- [STAT 135](/teaching#stat135) Concepts in Statistics

March 2013 - July 2014 **Tutor**, *School of Mathematics and
Statistics, The University of Sydney Australia*

- PHAR 2183 Therapeutic Principles (Mathematics and Statistics
Tutorial)
- MATH 1902 Linear Algebra (Advanced)
- MATH 1005 Statistics

### Workshops

June 11-12, 2018, *Software Carpentry: Shell, Git and R*, [**Berkeley Institute For Data Science (BIDS)**](https://bids.berkeley.edu/events/introduction-shell-git-and-r)

- Co-taught a 2-day Software Carpentry workshop to 40 researchers at UC Berkeley. 

- I taught half of each of the [Git](http://swcarpentry.github.io/git-novice/) and [R](http://swcarpentry.github.io/r-novice-inflammation/) lessons, corresponding to just over one third of the whole workshop.

April 4 2018, *Creating effective visualizations*, [**Environment and Society: Data Science for the 21st Century**](http://ds421.berkeley.edu/), UC Berkeley

- A 1.5 hour workshop on general principles for creating effective figures to 15 students in the National Science Foundation Research Traineeship (NRT) interdisciplinary graduate training program at UC Berkeley at the interface of data, social and natural sciences.

- [slides](http://slides.com/rebeccabarter/creating-effective-visualizations/fullscreen)

March 7 2018, *ggplot2 workshop*, [**Joint Genome Institute**](https://jgi.doe.gov/)

- A 1.5 hour workshop on visualization (focusing on ggplot2) at Joint Genome Institute for 40 staff members.

- [Github repo](https://github.com/rlbarter/ggplot-jgi).

Novmber 1 2017, *ggplot2 workshop*, [**The Hacker Within**](http://www.thehackerwithin.org/berkeley/), Berkeley Institute of Data Science

- A 1 hour workshop on ggplot2 for The Hacker Within series which is a weekly peer learning group for sharing skills and best practices for scientific computation and data science (approx 20 attendees).

- [Github repo](https://github.com/rlbarter/ggplot-jgi).

September 24 2017, *Visualization workshop*, [**R Ladies SF**](https://www.meetup.com/rladies-san-francisco/events/243118950/)

- A 30-minute workshop on visualization focusing on my superheat R package for 20 women at R Ladies (SF). 

- [Github repo](https://github.com/rlbarter/R-Ladies-Superheat)


May 3 2017, *The Role of Machine Learning in Computerized Decision Making for Clinical Decision Support Systems in Healthcare*, **UC Davis**

- A 2-hour workshop on the role of machine learning in CDS in healthcare at UC Davis. 

- [video](https://ucdhs.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=4bfc4adf-d592-4204-b463-3e58edaebf83), <a href="talks/Davis_Healthcare.pdf" title="Davis slides">slides</a>


April 14 2017, *Interactive Visualization in R*, **SGSA Seminar Series** 

- I ran a 1-hour workshop on interactive visualization in R for 15 graduate students in the statistics department. 

- [slides](/img/talks/interactive_vis_slides.html)


March 6 2017, *Documentation for R packages workshop*, [**Docathon 2017**](https://bids.berkeley.edu/events/docathon), Berkeley Institute of Data Science

- I ran a workshop for approximately 50 attendees on generating documentation for R packages as a part of the Docathon, an event highlighting the importance of software documentation. 

- [Github repo](https://github.com/rlbarter/R-documentation) 

- [video](https://www.youtube.com/watch?v=ikT_xnTFHC0)






------

## Community

2018 - Judge for the [SciPy 2018 John Hunter Excellence in Plotting Competition](https://scipy2018.scipy.org/ehome/299527/648119/?&speakerid=951914&language=eng&back=1)

- I was one of the Judges who chose the best visualizations from among the 38 entries to the John Hunter Excellence in Plotting Competition.

2018 - present *Certified Instructor*, [**Software Carpentry**](https://software-carpentry.org/)

- I am certified to run and teach software carpentry training workshops.


2017 - present *Founder and organizer*, [**Practical Statistics**](https://rlbarter.github.io/Practical-Statistics/)

- I founded and organized Practical Statistics: a group of graduate students, post-docs and research staff from the Statistics department, BIDS and D-Lab who meet to teach each other about statistical topics that are widely used in science, but rarely taught to statisticians.


2016/17 *Co-president*, [**Statistics Graduate Student Association (SGSA)**](http://sgsa.berkeley.edu/)

- Together with Kellie Ottoboni, I acted as the head of the graduate student body for the statistics department. 


------

## Talks

### Conference Talks

March 2017 - **Organ transplantation in the presence of HIV**, Berkeley Statistics Annual Research Symposium (BSTARS 2017). [<a href="talks/BSTARS_Transplantation.pdf" title="BSTARS">slides</a>]

June 2016 - **Superheat: An R package for visualizing complex data**, UseR! 2016.

March 2016 - **Superheat: An R package for complex data visualization**, Berkeley Statistics Annual Research Symposium (BSTARS 2016).

July 2014 - **Network-based biomarkers enhance classical approaches to prognostic gene expression signatures**, InCoB2014 (International Conference on Bioinformatics 2014).



### Other Talks


May 2017 - **Superheat: An R Package for Generating Beautiful, Extendable, Customizable Heatmaps**, Berkeley Institute for Data Science (BIDS) Faire 2017. [[video](https://youtu.be/iZqqe-R5c0I), <a href="talks/BIDS_Faire_Superheat.pdf" title="BIDS Faire slides">slides</a>]

April 2016 - **Correlation vs Causation: Why the Media Gets it Wrong!**, UC Berkeley Cal Day 2016. [<a href="talks/Cal_Day_Presentation.pdf" title="Cal Day">slides</a>]

October 2015 - **Supervised heatmaps: An R tool for complex data visualization**, Center for the Science of Information (CSoI) Virtual Brown Bag Seminar.

March 2013 - **Estimation in ACD and log-ACD models**, Big Day In, AMSI (Australian Mathematical Sciences Institute).