---
title: "Teaching Materials"
date: "2016-05-05T21:48:51-07:00"
---


<!-- If you want to work with me, or learn R or statistics from me, I'm available for private coaching and consulting! Email me at rebeccabarter@berkeley.edu to inquire. -->

I'm not currently teaching at Berkeley, but the courses I've taught are listed below.


## [Lecturer] Spring 2022: STAT 135 Concepts in Statistics

I was the lecturer for this core statistics undergraduate focusing on common methods in statistics such as MLE, the bootstrap, hypothesis testing and linear models.

The slides I created for this class can be found on GitHub: https://github.com/rlbarter/STAT135_Sp22



## [GSI/TA] Fall 2017: STAT 215A Statistical Models, Theory and Applications

A graudate course in applied statistics taught by Bin Yu. The course covers a wide range of topics that focus on critical thinking for using statistics in the wild. I taught a section each week where I either re-inforced content the students were learning in class, or ran tutorials in a variety of topics in R.

The materials that I prepared can be found in the following github repository: https://github.com/rlbarter/STAT-215A-Fall-2017.


## [GSI/TA] Spring 2015: STAT 135 Concepts in Statistics {#stat135}

An undergraduate course focusing on common methods in statistics such as MLE, the bootstrap, hypothesis testing and linear models. The instructor for this course was Joan Bruna. I taught a section each week on a topic related to what the students were learning in class.

<p>Lab 2: Confidence intervals, MLE and the delta method <a href="pdf/Lab2.pdf" title="Lab 2">(pdf)</a></p>
<p>Lab 3: Asymptotic MLE and the method of moments <a href="pdf/Lab3.pdf" title="Lab 3">(pdf)</a></p>
<p>Lab 4: Recap, efficiency, sufficiency, bias-variance trade-off (Rao-Blackwell), Bayesian inference <a href="pdf/Lab4.pdf" title="Lab 4">(pdf)</a></p>
<p>Lab 5: Bootstrapping and hypothesis testing <a href="pdf/Lab5.pdf" title="Lab 5">(pdf)</a></p>
<p>Lab 6: Duality of hypothesis testing and confidence intervals, GLRT, Pearson Chi-squared tests and Q-Q plots <a href="pdf/Lab6.pdf" title="Lab 6">(pdf)</a></p>
<p>Lab 7: Distributions derived from the normal distribution, and comparing independent samples <a href="pdf/Lab7.pdf" title="Lab 7">(pdf)</a></p>
<p>Lab 8: Hypothesis testing review, Mann-Whitney test by normal approximation, and Wilcoxon signed rank test <a href="pdf/Lab8.pdf" title="Lab 8">(pdf)</a></p>
<p>Lab 9: Multiple testing, one-way ANOVA and Kruskal-Wallis <a href="pdf/Lab9.pdf" title="Lab 9">(pdf)</a></p>
<p>Lab 10: Two-way ANOVA, randomized block design and Friedman's test <a href="pdf/Lab10.pdf" title="Lab 10">(pdf)</a></p>
<p>Lab 11: Tests for categorical data (Fisher's exact test, Chi-squared tests for homogeneity and independence) and linear regression <a href="pdf/Lab11.pdf" title="Lab 11">(pdf)</a></p>
<p>Lab 12: Multiple linear regression (matrix form), residual analysis and inference for OLS <a href="pdf/Lab12.pdf" title="Lab 12">(pdf)</a></p>
<p>Lab 13:  Linear regression, multivariate random variables, prediction, logistic regression and the delta-method <a href="pdf/Lab13.pdf" title="Lab 13">(pdf)</a></p>
<p>Review: Hypothesis testing flow chart <a href="pdf/Hypothesis_testing_flow_mean.pdf" title="Hypothesis Testing Flow Chart">(pdf)</a></p>

