---
title: "Resources that are useful"
date: "2018-08-30T21:48:51-07:00"
---

Web stuff

- **Website**: I wrote my website using [blogdown](https://bookdown.org/yihui/blogdown/) and host it using [netlify](https://www.netlify.com/). I have previously used both Jekyll and Hugo hosted on github pages, but overall find the blogdown + netlify combination to be much more straightforward. I wrote a [blog post](http://www.rebeccabarter.com/blog/2017-06-29-website/) on how I made my website a while ago.

- **Web development**: I've been making my way through Joel Ross and Mike Freeman's course book on [Client-Side Web Development](https://info343.github.io/) to learn the absolute basics of web development (namely html, css, and javascript). It's super easy to read and filled with examples. 

- **D3.js**: By far the best resource I've found by far for learning D3 is Scott Murray's [Interactive Data Visualization for the Web: An Introduction to Designing with D3](https://www.amazon.com/gp/product/1491921285/ref=dbs_a_def_rwt_bibl_vppi_i0).

Stats stuff 

- **Causal Inference**: When I started learning about causal inference, I found most of the papers totally unintelligible. The best resource I found for learning the basics of causal inference was Imbens and Rubin's [Causal Inference for Statistics, Social, and Biomedical Sciences: An Introduction](https://www.amazon.com/Causal-Inference-Statistics-Biomedical-Sciences/dp/0521885884), which was surprisingly accessible.

Visualization stuff

- **Colours**: My favourite way to choose colors for a plot is a website called https://coolors.co/, which randomly generates appealing color palettes for you to choose from. Just hit the space bar to generate a new palette!

- **Data viz best practices**: I absolutely loved Cole Nussbaumer Knaflic's [Storytelling with Data: A Data Visualization Guide for Business Professionals](https://www.amazon.com/gp/product/1119002257/ref=dbs_a_def_rwt_bibl_vppi_i0). I totally bought it on a whim a couple of years ago, and surprisingly learnt a huge amount. This book made me a lot more thoughtful about the visualizations that I produce.

R stuff

- **Tidyverse**: The resource that I usually point people towards for learning the tidyverse is Garrett Grolemund and Hadley Wickham's [R for Data Science](http://r4ds.had.co.nz/).

- **R packages**: When I made my first R package, Hadley Wickham's [book on R packages](http://r-pkgs.had.co.nz/) was indispensable!

Presentation and communication

- **Slides**: I use [slides.com](https://slides.com/) to make all my slides. Slides.com makes it super easy to make impressive reveal.js presentations without having to write any JavaScript! No more Google Docs! (I have a widely known hatered of LaTeX beamer slides which encourage all text and no visuals).

