---
title: "About Rebecca"
type: "about"
date: "2016-05-05T21:48:51-07:00"
---

Hi there! I'm Rebecca Barter. I'm so glad you've made it to my page.

I'm currently a third-year PhD student in the [Department of Statistics](http://statistics.berkeley.edu) at UC Berkeley, as well as a Data Science Fellow at the [Berkeley Institute for Data Science (BIDS)](https://bids.berkeley.edu). I am jointly advised by Professors [Bin Yu](https://www.stat.berkeley.edu/~binyu/Site/Welcome.html) (UC Berkeley),[ Jasjeet Sekhon](http://sekhon.berkeley.edu) (UC Berkeley) and [Minnie Sarwal](http://sarwallab.surgery.ucsf.edu) (UCSF). Together with [Kellie Ottoboni](http://www.stat.berkeley.edu/~kellieotto/), I am the co-president of the [Statistics Graduate Student Association](http://sgsa.berkeley.edu).

Prior to arriving at UC Berkeley, I was an undergraduate, and subsequently a research assistant with [Professor Jean Yee Hwa Yang](http://www.maths.usyd.edu.au/u/jeany/), at [The University of Sydney](https://sydney.edu.au/) in Australia, graduating in 2013 with Bachelor of Science (Advanced) and the University Medal in Statistics.

I am interested in a variety of problems in applied statistics primarily with applications in medicine, and am currently working on several projects related to data visualization, high dimensional (possibly, but probably not, "big") data analysis and causal inference. My primary project is in collaboration with the Sarwal lab in the Department of Surgery at UCSF where we are evaluating large quantities of data with the goal of predicting acute rejection in HIV-positive kidney transplant patients.

I am the author of the [superheat](https://github.com/rlbarter/superheat) R package for creating beautiful and customizable heatmaps in R.

Having an underlying enthusiasm for demystifying the wonderful world of statistics, I tend to spend a lot of time communicating the philosophy and methodology of statistics to others via both teaching and writing. In particular, I am currently satisfying my craving for educating others by co-authoring a book on data science together with my advisor, Bin Yu.

I usually spend my free time out hiking, knitting, practicing yoga or making music.
